import CONFIG from '@/config/config.js'

let IMAGE_LIST = {
  Page: {
    Empty: {
      Empty: '/page/empty/image_empty.png',
      EmptyTable: '/page/empty/image_table_empty.png',
      EmptyLive: '/page/empty/image_empty_live.png',
      EmptyMatchLive: '/page/empty/image_empty_live_match.png',
      EmptyMessage: '/page/empty/image_empty_message.png',
      EmptySearch: '/page/empty/image_empty_search.png',
      EmptyRoom: '/page/empty/image_table_empty.png',
      EmptyRoomDefect: '/page/empty/image_table_empty.png',
      EmptyTeam: '/page/empty/image_team_empty.png',
      EmptyVideo: '/page/empty/image_empty_video.png'
    },

    Login: {
      CountDown: '/page/login/icon_count_down.png',
      LoginClose: '/page/login/icon_close_black.png',
      LoginDefault: '/page/login/image_login_default.png'
    },

    Layout: {
      LangDown: '/page/layout/icon_lang_down.png',
      BannerAdv: '/page/layout/image_banner_adv.png',
      BannerFooterAdv: '/page/layout/image_banner_footer_adv.png',
      QRCode: '/page/layout/image_qr_code.png',
      OleLogo: '/page/layout/image_ole_logo.png',
      MenuDown: '/page/layout/icon_menu_down.png',
      GlobalSearch: '/page/layout/icon_global_search.png',
      Facebook: '/page/layout/icon_facebook.png',
      TikTok: '/page/layout/icon_tik_tok.png',
      Line: '/page/layout/icon_line.png',
      Twitter: '/page/layout/icon_twitter.png',
      VKontakte: '/page/layout/icon_vkontakte.png',
      Youtube: '/page/layout/icon_youtube.png',
      AdvClose: '/page/layout/icon_adv_close.png',
      FacebookShare: '/page/layout/icon_facebook_share.png',
      TwitterShare: '/page/layout/icon_twitter_share.png',
      WhatAppShare: '/page/layout/icon_whatApp_share.png',
      VKontakteShare: '/page/layout/icon_vkontakte_share.png',
      LineShare: '/page/layout/icon_line_share.png',
      SkypeShare: '/page/layout/icon_skype_share.png',
      TelegramShare: '/page/layout/icon_telegram_share.png',
      MessengerShare: '/page/layout/icon_messenger_share.png',
      LineIcon: '/page/layout/icon_line_qd.png',
      AppIcon: '/page/layout/icon_app_qd.png',
      AppIconGif: '/page/layout/icon_app_qd.gif',
      ScrollTop: '/page/layout/icon_layout_scroll.png',
      ImgLoad: '/page/layout/image_load.png',
      CheckActive: '/page/layout/image_check_active.png',
      Check: '/page/layout/image_check.png',
      Out: '/page/layout/image_out.png',
      Ing: '/page/layout/image_ing.png',
      SwitchActive: '/page/layout/icon_switch_true.png',
      Switch: '/page/layout/icon_switch_false.png',
      MoreImg: '/page/layout/image_more_img.png'
    },

    Home: {
      HomeLive: '/page/home/icon_Living.png',
      HomeAnchorLive: '/page/home/icon_live_anchor.png',
      TopLiving: '/page/home/icon_living_top.png',
      Views: '/page/home/icon_views.png',
      Notify: '/page/home/icon_notify.png',
      Living: '/page/home/living.png',
      Calendar: '/page/home/icon_calendar.png',
      LeftLink: '/page/home/icon_left_link.png',
      HomeTeam: '/page/home/icon_home_team.png',
      AwyTeam: '/page/home/icon_awy_team.png',
      Notice: '/page/home/icon_notice.png',
      topAnchor: '/page/home/icon_home_topAnchor.png',
      topMoment: '/page/home/icon_home_topMoment.png',
      toNews: '/page/home/icon_home_topNews.png',
      topScore: '/page/home/icon_home_topScore.png',
      topVideo: '/page/home/icon_home_topVideo.png',
      topAnchorSchedule: '/page/home/icon_anchor_schedule.png',
      topLiving: '/page/home/icon_home_living.png',
      ContactUs: '/page/home/image_contact_us.png',
      DialogHome: '/page/home/image_home_dialog.png',
      LiveBg: '/page/home/live_bg.png',
      ToLive: '/page/home/tolive.png',
      Fllowing: '/page/home/Fllowing.png',
      NotFllowing: '/page/home/notFollowing.png',
      HomeWeek: '/page/home/icon_week_home.png'
    },

    Match: {
      ANCHOR: '/page/match/image_ANCHOR.png',
      ANCHOR_S: '/page/match/image_ANCHOR_S.png',
      ALL: '/page/match/ALL.png',
      ALL_S: '/page/match/ALL_S.png',
      FOOTBALL_S: '/page/match/image_FOOTBALL_S.png',
      FOOTBALL: '/page/match/image_FOOTBALL.png',
      BASKETBALL_S: '/page/match/image_BASKETBALL_S.png',
      BASKETBALL: '/page/match/image_BASKETBALL.png',
      BASEBALL_S: '/page/match/image_BASEBALL_S.png',
      BASEBALL: '/page/match/image_BASEBALL.png',
      BOXING_S: '/page/match/image_BOXING_S.png',
      BOXING: '/page/match/image_BOXING.png',
      CRICKET_S: '/page/match/image_CRICKET_S.png',
      CRICKET: '/page/match/image_CRICKET.png',
      EFOOTBALL_S: '/page/match/image_EFOOTBALL_S.png',
      EFOOTBALL: '/page/match/image_EFOOTBALL.png',
      EBASKETBALL_S: '/page/match/image_EBASKETBALL_S.png',
      EBASKETBALL: '/page/match/image_EBASKETBALL.png',
      ESPORTS_S: '/page/match/image_ESPORTS_S.png',
      ESPORTS: '/page/match/image_ESPORTS.png',
      ICEHOCKEY_S: '/page/match/image_ICEHOCKEY_S.png',
      ICEHOCKEY: '/page/match/image_ICEHOCKEY.png',
      RUGBY_S: '/page/match/image_RUGBY_S.png',
      RUGBY: '/page/match/image_RUGBY.png',
      SNOOKER_S: '/page/match/image_SNOOKER_S.png',
      SNOOKER: '/page/match/image_SNOOKER.png',
      TABLETENNIS_S: '/page/match/image_TABLETENNIS_S.png',
      TABLETENNIS: '/page/match/image_TABLETENNIS.png',
      TENNIS_S: '/page/match/image_TENNIS_S.png',
      TENNIS: '/page/match/image_TENNIS.png',
      VOLLEYBALL_S: '/page/match/image_VOLLEYBALL_S.png',
      VOLLEYBALL: '/page/match/image_VOLLEYBALL.png',
      BADMINTON_S: '/page/match/image_BADMINTON_S.png',
      BADMINTON: '/page/match/image_BADMINTON.png',
      GOLF_S: '/page/match/image_GOLF_S.png',
      GOLF: '/page/match/image_GOLF.png',
      FIELDHOCKEY_S: '/page/match/image_FIELDHOCKEY_S.png',
      FIELDHOCKEY: '/page/match/image_FIELDHOCKEY.png',
      MMA_S: '/page/match/image_MMA_S.png',
      MMA: '/page/match/image_MMA.png',
      FUTSAL_S: '/page/match/image_FUTSAL_S.png',
      FUTSAL: '/page/match/image_FUTSAL.png'
    },

    Room: {
      OngGift: '/page/room/icon_on_gift.png',
      Reward: '/page/room/icon_reward.png',
      Block: '/page/room/icon_room_block.png',
      ActiveBlock: '/page/room/icon_room_active_block.png',
      Comment: '/page/room/icon_room_comment.png',
      ActiveComment: '/page/room/icon_room_active_comment.png',
      DelComment: '/page/room/icon_room_del_comment.png',
      ActiveDelComment: '/page/room/icon_room_active_del_comment.png',
      Speech: '/page/room/icon_room_speech.png',
      ActiveSpeech: '/page/room/icon_room_active_speech.png',
      CornerKick: '/page/room/icon_room_cornerKick.png',
      YellowCard: '/page/room/icon_room_yellow.png',
      RedCard: '/page/room/icon_room_red.png',
      Facebook: '/page/room/icon_room_facebook.png',
      FBBg: '/page/room/icon_room_FBbg.png',
      Line: '/page/room/icon_room_line.png',
      RoomNotice: '/page/room/icon_room_notice.png',
      Share: '/page/room/icon_room_share.png',
      Up: '/page/room/icon_room_up.png',
      Down: '/page/room/icon_room_down.png',
      WhactApp: '/page/room/icon_room_whactapp.png',
      Submit: '/page/room/icon_submit.png',
      Hot: '/page/room/icon_room_hot.png',
      Time: '/page/room/icon_room_time.png',
      Lock: '/page/room/icon_room_lock.png',
      DanMuActive: '/page/room/image_danmu_active.png',
      DanMu: '/page/room/image_danmu.png'
    },

    Incidents: {
      Goal: '/page/incidents/image_goal.png',
      OwnGoal: '/page/incidents/image_own_goal.png',
      Penalty: '/page/incidents/image_penalty.png',
      MissedPenalty: '/page/incidents/image_missed_penalty.png',
      Assist: '/page/incidents/image_assist.png',
      YellowCard: '/page/incidents/image_yellow_card.png',
      RedCard: '/page/incidents/image_red_card.png',
      SecondYellowCard: '/page/incidents/image_second_yellow_card.png',
      Substitution: '/page/incidents/image_substitution.png',
      VAR: '/page/incidents/image_VAR.png',
      Up: '/page/incidents/image_up.png',
      Down: '/page/incidents/image_down.png',
      OddsUp: '/page/incidents/img_odds_up.png',
      OddsDown: '/page/incidents/img_odds_down.png'
    },
    
    Substitution: {
      Up: "/live/greenup.png",
      Down: "/live/changedown.png",
      Goal: "/live/jinqiu.png",
      OwnGoal: "/live/wulong.png",
      Penalty: "/live/dianqiu.png",
      MissedPenalty: "/live/dianbu.png",
      Assist: "/live/zhugong.png",
      VAR: "/live/VAR.png",
      YellowCard: "/live/huangpai.png",
      RedCard: "/live/hongpai.png",
      SecondYellow: "/static/image/page/incidents/image_second_yellow_card.png",
      Corner: "/live/jiaoqiu.png",
      InjuryTime: "/live/shoushang.png",
      Substitution: "/live/huanren.png",
    },
   
    MatchScore: {
      videoBlack: '/page/matchScore/icon_video_black.png',
      AllBlack: '/page/matchScore/icon_all_black.png',
      MicroBlack: '/page/matchScore/icon_micro_black.png',
      TimeBlack: '/page/matchScore/icon_time_black.png',
      videoWhite: '/page/matchScore/icon_video_white.png',
      AllWhite: '/page/matchScore/icon_all_white.png',
      MicroWhite: '/page/matchScore/icon_micro_white.png',
      TimeWhite: '/page/matchScore/icon_tine_white.png',
      FTBlock: '/page/matchScore/icon_match_FT_block.png',
      FTWhite: '/page/matchScore/icon_match_FT_white.png',
      MatchDefault: '/page/matchScore/icon_match_default.png'
    },

    News: {
      Share: '/page/news/icon_share.png',
      Nice: '/page/news/icon_nice.png',
      NiceActive: '/page/news/icon_nice_active.png',
      ChangeIt: '/page/news/icon_change_it.png',
      ThumbUp: '/page/news/thumb-up.png',
      ThumbUped: '/page/news/thumb-uped.png',
      VideoPlay: '/page/news/image_video_play.png'
    },

    Live: {
      TeamIcon: '/page/live/icon_live_team.png',
      FOOTBALL: '/page/live/FOOTBALL.jpg',
      BASKETBALL: '/page/live/BASKETBALL.jpg',
      BASEBALL: '/page/live/BASEBALL.jpg',
      BOXING: '/page/live/BOXING.jpg',
      CRICKET: '/page/live/CRICKET.jpg',
      EFOOTBALL: '/page/live/EFOOTBALL.jpg',
      EBASKETBALL: '/page/live/EBASKETBALL.jpg',
      ESPORTS: '/page/live/ESPORTS.jpg',
      ICEHOCKEY: '/page/live/ICEHOCKEY.jpg',
      RUGBY: '/page/live/RUGBY.jpg',
      SNOOKER: '/page/live/SNOOKER.jpg',
      TABLETENNIS: '/page/live/TABLETENNIS.jpg',
      TENNIS: '/page/live/TENNIS.jpg',
      VOLLEYBALL: '/page/live/VOLLEYBALL.jpg',
      BADMINTON: '/page/live/BADMINTON.jpg',
      GOLF: '/page/live/GOLF.jpg',
      FIELDHOCKEY: '/page/live/FIELDHOCKEY.jpg',
      MMA: '/page/live/MMA.jpg',
      FUTSAL: '/page/live/FUTSAL.jpg',
      LiveLogo: '/page/live/icon_ole_liveLogo.png',
      SubscribeSuccess: '/page/live/image_subscribe_success.png',
      Subscribe: '/page/live/image_subscribe.png',
      FT: '/page/live/image_FT.png',
      Activebg: '/page/live/activebg.png',
      Liveicon: '/page/live/live.png',
      Videoicon: '/page/live/videoicon.png',
      Readicon: '/page/live/readicon.png',
      Watchicon: '/page/live/watchicon.png',
      Share: "/page/live/share.png",
      Start: "/page/live/start.png",
      Started: "/page/live/started.png",
      ThumbUp: "/page/live/thumb-up.png",
      ThumbUped: "/page/live/thumb-uped.png",
      BillAnchor: "/page/live/liveicon.png",
      BillBt: "/page/live/billBt.png",
      VipCrown: "/page/live/vip-crown.png",
      Close: "/page/live/close.png",
      GetDiamond: "/page/live/get_diamond.gif",
      Fire:'/page/live/fire.png',
      LiveBackground: "/page/live/live_background.png",
    },

    User: {
      Dollar: '/page/user/icon_dollar.png',
      Step1: '/page/user/image_step1.png',
      Step2: '/page/user/image_step2.png',
      Step3: '/page/user/image_step3.png',
      ActiveStep1: '/page/user/image_active_step1.png',
      ActiveStep2: '/page/user/image_active_step2.png',
      ActiveStep3: '/page/user/image_active_step3.png',
      setLive: '/page/user/image_live_set.png',
      PersonalData: '/page/user/icon_personal_data.png',
      ActivePersonalData: '/page/user/icon_active_personal_data.png',
      Personage: '/page/user/icon_personage.png',
      ActivePersonage: '/page/user/icon_active_personage.png',
      Message: '/page/user/icon_message.png',
      ActiveMessage: '/page/user/icon_active_message.png',
      AnchorAuth: '/page/user/icon_anchor.png',
      ActiveAnchorAuth: '/page/user/icon_active_anchor.png',
      Attention: '/page/user/icon_attention.png',
      ActiveAttention: '/page/user/icon_active_attention.png',
      Pay: '/page/user/icon_pay.png',
      ActivePay: '/page/user/icon_active_pay.png',
      PayDetail: '/page/user/icon_pay_detail.png',
      ActivePayDetail: '/page/user/icon_active_pay_detail.png',
      Reward: '/page/user/icon_reward.png',
      ActiveReward: '/page/user/icon_active_reward.png',
      RewardDetail: '/page/user/icon_reward_detail.png',
      ActiveRewardDetail: '/page/user/icon_active_reward_detail.png',
      LiveRecord: '/page/user/icon_live_record.png',
      ActiveLiveRecord: '/page/user/icon_active_live_record.png',
      GoLive: '/page/user/icon_go_live.png',
      ActiveGoLive: '/page/user/icon_active_go_live.png',
      Upload: '/page/user/icon_upload.png',
      AddPass: '/page/user/icon_add_pass.png',
      messageUp: '/page/user/icon_message_up.png',
      messageDown: '/page/user/icon_message_down.png',
      MessageLight: '/page/user/icon_notice.png',
      Delete: '/page/user/icon_delete.png',
      Follow: '/page/user/icon_follow.png',
      Recommend: '/page/user/icon_recommend.png',
      PayActive: '/page/user/icon_pay_active.png',
      PayLoading: '/page/user/image_pay_loading.png',
      Bg: '/page/user/bg.png',
      DBg: '/page/user/dbg.png',
      Diamond: '/page/user/diamond.png',
      Calendar: "/page/user/calendar.png",
      Letter: "/page/user/letter.png",
      Sign: "/page/user/sign.png",
      Invite: "/page/user/invite.png",
      SaveIcon: "/page/user/saveicon.png",
    },

    Chat: {
      Close: '/page/chat/icon_chat_close.png',
      Emo: '/page/chat/icon_chat_emo.png',
      Notice: '/page/chat/icon_chat_notice.png',
      Photo: '/page/chat/icon_chat_photo.png',
      User: '/page/chat/image_user.png',
      Quote: '/page/chat/icon_chat_quote.png',
      Gif1: '/page/chat/gif1.gif',
      Gif2: '/page/chat/gif2.gif',
      Gif3: '/page/chat/gif3.gif',
      ChatLeft: '/page/chat/icon_chat_left.png'
    },

    App: {
      Android: '/page/app/image_app_android.png',
      Ios: '/page/app/image_app_ios.png',
      Appbg: '/page/app/bg.png',
      Bg: '/page/app/image_app_bg.jpg',
      Code: '/page/app/image_app_code.png',
      CodeBg: '/page/app/image_app_codeBg.png',
      SuCai: '/page/app/image_app_sucai.png',
      IsoZH1: '/page/app/image_ios_zh_1.png',
      IsoZH2: '/page/app/image_ios_zh_2.png',
      IsoZH3: '/page/app/image_ios_zh_3.png',
      IsoZH4: '/page/app/image_ios_zh_4.png',
      IsoZH5: '/page/app/image_ios_zh_5.png',
      IsoEN1: '/page/app/image_ios_en_1.png',
      IsoEN2: '/page/app/image_ios_en_2.png',
      IsoEN3: '/page/app/image_ios_en_3.png',
      IsoEN4: '/page/app/image_ios_en_4.png',
      IsoEN5: '/page/app/image_ios_en_5.png',
      IsoTH1: '/page/app/image_ios_th_1.png',
      IsoTH2: '/page/app/image_ios_th_2.png',
      IsoTH3: '/page/app/image_ios_th_3.png',
      IsoTH4: '/page/app/image_ios_th_4.png',
      IsoTH5: '/page/app/image_ios_th_5.png',
      IsoTH6: '/page/app/image_ios_th_6.png',
      IsoID1: '/page/app/image_ios_id_1.png',
      IsoID2: '/page/app/image_ios_id_2.png',
      IsoID3: '/page/app/image_ios_id_3.png',
      IsoID4: '/page/app/image_ios_id_4.png',
      IsoID5: '/page/app/image_ios_id_5.png',
      IsoID6: '/page/app/image_ios_id_6.png',
      IsoVI1: '/page/app/image_ios_vi_1.png',
      IsoVI2: '/page/app/image_ios_vi_2.png',
      IsoVI3: '/page/app/image_ios_vi_3.png',
      IsoVI4: '/page/app/image_ios_vi_4.png',
      IsoVI5: '/page/app/image_ios_vi_5.png',
      IsoVI6: '/page/app/image_ios_vi_6.png',
      IsoVI7: '/page/app/image_ios_vi_7.png',
      IsoVI8: '/page/app/image_ios_vi_8.png',
      IsoVI9: '/page/app/image_ios_vi_9.png',
      AnZH1: '/page/app/image_an_zh_1.png',
      AnZH2: '/page/app/image_an_zh_2.png',
      AnZH3: '/page/app/image_an_zh_3.png',
      AnZH4: '/page/app/image_an_zh_4.png',
      AnZH5: '/page/app/image_an_zh_5.png',
      AnZH6: '/page/app/image_an_zh_6.png',
      AnEN1: '/page/app/image_an_en_1.png',
      AnEN2: '/page/app/image_an_en_2.png',
      AnEN3: '/page/app/image_an_en_3.png',
      AnEN4: '/page/app/image_an_en_4.png',
      AnEN5: '/page/app/image_an_en_5.png',
      AnTH1: '/page/app/image_an_th_1.png',
      AnTH2: '/page/app/image_an_th_2.png',
      AnTH3: '/page/app/image_an_th_3.png',
      AnID1: '/page/app/image_an_id_1.png',
      AnID2: '/page/app/image_an_id_2.png',
      AnID3: '/page/app/image_an_id_3.png',
      AnVI1: '/page/app/image_an_vi_1.png',
      AnVI2: '/page/app/image_an_vi_2.png',
      AnVI3: '/page/app/image_an_vi_3.png',
      LeftArrow: '/page/app/icon_left_arrow.png',
      RightArrow: '/page/app/icon_right_arrow.png'
    }
  },
  Icon: {
    Lang: {
      zhCN: '/lang/image_zh_CN.png',
      enUS: '/lang/image_en_US.png',
      thTH: '/lang/image_th_TH.png',
      idID: '/lang/image_id_ID.png',
      viVN: '/lang/image_vi_VN.png'
    }
  }
}

// function image() {
//   for (let item in IMAGE_LIST) {
//     if (IMAGE_LIST[item] instanceof Object) {
//       IMAGE_LIST[item] = imageForeach(obj[item])
//     } else {
//       IMAGE_LIST[item] = splitImageUrl(obj[item])
//     }
//   }
// }

function replaceImageUrl() {
  for (let item in IMAGE_LIST) {
    for (let image1 in IMAGE_LIST[item]) {
      if (IMAGE_LIST[item][image1] instanceof Object) {
        for (let image2 in IMAGE_LIST[item][image1]) {
          IMAGE_LIST[item][image1][
            image2
          ] = `${CONFIG.IMAGE_PREFIX_URL}${IMAGE_LIST[item][image1][image2]}`
        }
      } else {
        IMAGE_LIST[item][
          image1
        ] = `${CONFIG.IMAGE_PREFIX_URL}${IMAGE_LIST[item][image1]}`
      }
    }
  }
}

replaceImageUrl(IMAGE_LIST)

export default IMAGE_LIST
